global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "nexuscache"
    static_configs:
      - targets:
          - "svc1:9100"
          - "svc2:9100"
          - "svc3:9100"
        labels:
          env: "docker"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
